In [39]:
import pandas as pd
import numpy as np

working_data = pd.read_csv("employee_survey.csv")
#workig_data.head()
#working_data.tail()
working_data.info()
#working_data.describe()
df = pd.DataFrame(working_data)
df
#series = pd.Series([1, 2, 3, 4, 5])
#series
#get all data sample under gender
#working_data.loc[1,"Gender"]
#working_data.size
#working_data.shape
#working_data.ndim
working_data.empty

<class 'pandas.DataFrame'>
RangeIndex: 3025 entries, 0 to 3024
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   EmpID                  3025 non-null   int64
 1   Gender                 3025 non-null   str
 2   Age                    3025 non-null   int64
 3   MaritalStatus          3025 non-null   str
 4   JobLevel               3025 non-null   str
 5   Experience             3025 non-null   int64
 6   Dept                   3025 non-null   str
 7   EmpType                3025 non-null   str
 8   WLB                    3025 non-null   int64
 9   WorkEnv                3025 non-null   int64
 10  PhysicalActivityHours  3025 non-null   float64
 11  Workload               3025 non-null   int64
 12  Stress                 3025 non-null   int64
 13  SleepHours             3025 non-null   float64
 14  CommuteMode            3025 non-null   str
 15  CommuteDistance        3025 non-null   int64
 16  NumCompanies           3025 non-null   int64
 17  TeamSize               3025 non-null   int64
 18  NumReports             3025 non-null   int64
 19  EduLevel               3025 non-null   str
 20  haveOT                 3025 non-null   bool
 21  TrainingHoursPerYear   3025 non-null   float64
 22  JobSatisfaction        3025 non-null   int64
dtypes: bool(1), float64(3), int64(12), str(7)
memory usage: 523.0 KB

False

In [40]:
working_data.describe

<bound method NDFrame.describe of       EmpID  Gender  Age MaritalStatus        JobLevel  Experience       Dept  \
0         6    Male   32       Married             Mid           7         IT
1        11  Female   34       Married             Mid          12    Finance
2        33  Female   23        Single  Intern/Fresher           1  Marketing
3        20  Female   29       Married          Junior           6         IT
4        28   Other   23        Single          Junior           1      Sales
...     ...     ...  ...           ...             ...         ...        ...
3020   2070    Male   47       Married            Lead          16  Marketing
3021   2072  Female   47       Married            Lead           8         IT
3022   2145    Male   41       Married            Lead          17         IT
3023   2168  Female   54       Married            Lead          16         IT
3024   2183  Female   44       Married            Lead          22  Marketing

        EmpType  WLB  WorkEnv  ...  SleepHours       CommuteMode  \
0     Full-Time    1        1  ...         7.6               Car
1     Full-Time    1        1  ...         7.9               Car
2     Full-Time    2        4  ...         6.5         Motorbike
3      Contract    2        2  ...         7.5  Public Transport
4     Part-Time    3        1  ...         4.9               Car
...         ...  ...      ...  ...         ...               ...
3020  Part-Time    1        3  ...         6.8  Public Transport
3021   Contract    3        1  ...         6.9               Car
3022  Full-Time    1        1  ...         6.1  Public Transport
3023  Full-Time    1        5  ...         7.7  Public Transport
3024  Full-Time    3        3  ...         6.2               Car

      CommuteDistance  NumCompanies TeamSize  NumReports  EduLevel  haveOT  \
0                  20             3       12           0  Bachelor    True
1                  15             4       11           0  Bachelor   False
2                  17             0       30           0  Bachelor    True
3                  13             2        9           0  Bachelor    True
4                  20             0        7           0  Bachelor   False
...               ...           ...      ...         ...       ...     ...
3020               15             8       28           8    Master   False
3021               28             8       21           8    Master    True
3022                9             6       23           3    Master    True
3023               18            10       30           7    Master    True
3024               10             7       29           4       PhD   False

      TrainingHoursPerYear JobSatisfaction
0                     33.5               5
1                     36.0               5
2                     10.5               5
3                     23.0               5
4                     20.5               5
...                    ...             ...
3020                  58.0               1
3021                  54.0               1
3022                  58.5               1
3023                  58.0               1
3024                  61.0               1

[3025 rows x 23 columns]>

In [41]:
working_data.size

69575

In [42]:
working_data.head()

,EmpID,Gender,Age,MaritalStatus,JobLevel,Experience,Dept,EmpType,WLB,WorkEnv,...,SleepHours,CommuteMode,CommuteDistance,NumCompanies,TeamSize,NumReports,EduLevel,haveOT,TrainingHoursPerYear,JobSatisfaction
0,6,Male,32,Married,Mid,7,IT,Full-Time,1,1,...,7.6,Car,20,3,12,0,Bachelor,True,33.5,5
1,11,Female,34,Married,Mid,12,Finance,Full-Time,1,1,...,7.9,Car,15,4,11,0,Bachelor,False,36.0,5
2,33,Female,23,Single,Intern/Fresher,1,Marketing,Full-Time,2,4,...,6.5,Motorbike,17,0,30,0,Bachelor,True,10.5,5
3,20,Female,29,Married,Junior,6,IT,Contract,2,2,...,7.5,Public Transport,13,2,9,0,Bachelor,True,23.0,5
4,28,Other,23,Single,Junior,1,Sales,Part-Time,3,1,...,4.9,Car,20,0,7,0,Bachelor,False,20.5,5

In [43]:
working_data.info

<bound method DataFrame.info of       EmpID  Gender  Age MaritalStatus        JobLevel  Experience       Dept  \
0         6    Male   32       Married             Mid           7         IT
1        11  Female   34       Married             Mid          12    Finance
2        33  Female   23        Single  Intern/Fresher           1  Marketing
3        20  Female   29       Married          Junior           6         IT
4        28   Other   23        Single          Junior           1      Sales
...     ...     ...  ...           ...             ...         ...        ...
3020   2070    Male   47       Married            Lead          16  Marketing
3021   2072  Female   47       Married            Lead           8         IT
3022   2145    Male   41       Married            Lead          17         IT
3023   2168  Female   54       Married            Lead          16         IT
3024   2183  Female   44       Married            Lead          22  Marketing

        EmpType  WLB  WorkEnv  ...  SleepHours       CommuteMode  \
0     Full-Time    1        1  ...         7.6               Car
1     Full-Time    1        1  ...         7.9               Car
2     Full-Time    2        4  ...         6.5         Motorbike
3      Contract    2        2  ...         7.5  Public Transport
4     Part-Time    3        1  ...         4.9               Car
...         ...  ...      ...  ...         ...               ...
3020  Part-Time    1        3  ...         6.8  Public Transport
3021   Contract    3        1  ...         6.9               Car
3022  Full-Time    1        1  ...         6.1  Public Transport
3023  Full-Time    1        5  ...         7.7  Public Transport
3024  Full-Time    3        3  ...         6.2               Car

      CommuteDistance  NumCompanies TeamSize  NumReports  EduLevel  haveOT  \
0                  20             3       12           0  Bachelor    True
1                  15             4       11           0  Bachelor   False
2                  17             0       30           0  Bachelor    True
3                  13             2        9           0  Bachelor    True
4                  20             0        7           0  Bachelor   False
...               ...           ...      ...         ...       ...     ...
3020               15             8       28           8    Master   False
3021               28             8       21           8    Master    True
3022                9             6       23           3    Master    True
3023               18            10       30           7    Master    True
3024               10             7       29           4       PhD   False

      TrainingHoursPerYear JobSatisfaction
0                     33.5               5
1                     36.0               5
2                     10.5               5
3                     23.0               5
4                     20.5               5
...                    ...             ...
3020                  58.0               1
3021                  54.0               1
3022                  58.5               1
3023                  58.0               1
3024                  61.0               1

[3025 rows x 23 columns]>

In [44]:
sample_size = working_data.sample(10)
sample_size

,EmpID,Gender,Age,MaritalStatus,JobLevel,Experience,Dept,EmpType,WLB,WorkEnv,...,SleepHours,CommuteMode,CommuteDistance,NumCompanies,TeamSize,NumReports,EduLevel,haveOT,TrainingHoursPerYear,JobSatisfaction
831,631,Female,27,Single,Junior,5,Operations,Part-Time,2,5,...,6.8,Public Transport,25,1,9,0,Bachelor,False,22.5,3
2906,1539,Male,47,Married,Lead,8,Legal,Full-Time,3,3,...,7.9,Motorbike,16,8,22,4,Bachelor,False,54.0,4
1725,2796,Male,31,Married,Mid,5,IT,Part-Time,4,5,...,5.2,Bike,4,3,11,0,Bachelor,True,32.5,5
1379,580,Other,26,Single,Junior,4,Operations,Part-Time,3,5,...,7.4,Walk,1,1,10,0,High School,False,22.0,5
1023,2659,Female,48,Married,Mid,10,Operations,Full-Time,1,2,...,6.2,Public Transport,23,8,13,0,Bachelor,False,35.0,3
196,2,Female,32,Single,Senior,10,HR,Full-Time,5,5,...,6.7,Motorbike,13,3,16,5,Bachelor,False,45.0,4
2609,1187,Female,32,Single,Senior,8,Operations,Part-Time,2,5,...,6.5,Walk,1,3,19,5,Bachelor,False,44.0,2
2833,2120,Other,43,Single,Senior,4,IT,Full-Time,3,1,...,7.3,Motorbike,5,7,25,8,Bachelor,True,42.0,1
390,1487,Female,35,Married,Mid,13,IT,Full-Time,3,5,...,6.3,Car,25,4,13,0,Bachelor,True,36.5,4
2951,2598,Male,44,Married,Lead,22,Sales,Contract,2,5,...,6.5,Motorbike,14,7,22,2,PhD,False,61.0,4

In [45]:
#Loop trough the sample_size, print label and value
for label, value in sample_size.items():
    print(label)
    print(value)

EmpID
831      631
2906    1539
1725    2796
1379     580
1023    2659
196        2
2609    1187
2833    2120
390     1487
2951    2598
Name: EmpID, dtype: int64
Gender
831     Female
2906      Male
1725      Male
1379     Other
1023    Female
196     Female
2609    Female
2833     Other
390     Female
2951      Male
Name: Gender, dtype: str
Age
831     27
2906    47
1725    31
1379    26
1023    48
196     32
2609    32
2833    43
390     35
2951    44
Name: Age, dtype: int64
MaritalStatus
831      Single
2906    Married
1725    Married
1379     Single
1023    Married
196      Single
2609     Single
2833     Single
390     Married
2951    Married
Name: MaritalStatus, dtype: str
JobLevel
831     Junior
2906      Lead
1725       Mid
1379    Junior
1023       Mid
196     Senior
2609    Senior
2833    Senior
390        Mid
2951      Lead
Name: JobLevel, dtype: str
Experience
831      5
2906     8
1725     5
1379     4
1023    10
196     10
2609     8
2833     4
390     13
2951    22
Name: Experience, dtype: int64
Dept
831     Operations
2906         Legal
1725            IT
1379    Operations
1023    Operations
196             HR
2609    Operations
2833            IT
390             IT
2951         Sales
Name: Dept, dtype: str
EmpType
831     Part-Time
2906    Full-Time
1725    Part-Time
1379    Part-Time
1023    Full-Time
196     Full-Time
2609    Part-Time
2833    Full-Time
390     Full-Time
2951     Contract
Name: EmpType, dtype: str
WLB
831     2
2906    3
1725    4
1379    3
1023    1
196     5
2609    2
2833    3
390     3
2951    2
Name: WLB, dtype: int64
WorkEnv
831     5
2906    3
1725    5
1379    5
1023    2
196     5
2609    5
2833    1
390     5
2951    5
Name: WorkEnv, dtype: int64
PhysicalActivityHours
831     1.2
2906    0.9
1725    3.3
1379    1.3
1023    0.0
196     3.5
2609    2.1
2833    1.3
390     2.9
2951    2.4
Name: PhysicalActivityHours, dtype: float64
Workload
831     5
2906    5
1725    1
1379    2
1023    4
196     4
2609    4
2833    5
390     3
2951    3
Name: Workload, dtype: int64
Stress
831     3
2906    1
1725    1
1379    1
1023    3
196     2
2609    3
2833    1
390     2
2951    1
Name: Stress, dtype: int64
SleepHours
831     6.8
2906    7.9
1725    5.2
1379    7.4
1023    6.2
196     6.7
2609    6.5
2833    7.3
390     6.3
2951    6.5
Name: SleepHours, dtype: float64
CommuteMode
831     Public Transport
2906           Motorbike
1725                Bike
1379                Walk
1023    Public Transport
196            Motorbike
2609                Walk
2833           Motorbike
390                  Car
2951           Motorbike
Name: CommuteMode, dtype: str
CommuteDistance
831     25
2906    16
1725     4
1379     1
1023    23
196     13
2609     1
2833     5
390     25
2951    14
Name: CommuteDistance, dtype: int64
NumCompanies
831     1
2906    8
1725    3
1379    1
1023    8
196     3
2609    3
2833    7
390     4
2951    7
Name: NumCompanies, dtype: int64
TeamSize
831      9
2906    22
1725    11
1379    10
1023    13
196     16
2609    19
2833    25
390     13
2951    22
Name: TeamSize, dtype: int64
NumReports
831     0
2906    4
1725    0
1379    0
1023    0
196     5
2609    5
2833    8
390     0
2951    2
Name: NumReports, dtype: int64
EduLevel
831        Bachelor
2906       Bachelor
1725       Bachelor
1379    High School
1023       Bachelor
196        Bachelor
2609       Bachelor
2833       Bachelor
390        Bachelor
2951            PhD
Name: EduLevel, dtype: str
haveOT
831     False
2906    False
1725     True
1379    False
1023    False
196     False
2609    False
2833     True
390      True
2951    False
Name: haveOT, dtype: bool
TrainingHoursPerYear
831     22.5
2906    54.0
1725    32.5
1379    22.0
1023    35.0
196     45.0
2609    44.0
2833    42.0
390     36.5
2951    61.0
Name: TrainingHoursPerYear, dtype: float64
JobSatisfaction
831     3
2906    4
1725    5
1379    5
1023    3
196     4
2609    2
2833    1
390     4
2951    4
Name: JobSatisfaction, dtype: int64

In [46]:
sample_size[sample_size['Age'] > 25]

,EmpID,Gender,Age,MaritalStatus,JobLevel,Experience,Dept,EmpType,WLB,WorkEnv,...,SleepHours,CommuteMode,CommuteDistance,NumCompanies,TeamSize,NumReports,EduLevel,haveOT,TrainingHoursPerYear,JobSatisfaction
831,631,Female,27,Single,Junior,5,Operations,Part-Time,2,5,...,6.8,Public Transport,25,1,9,0,Bachelor,False,22.5,3
2906,1539,Male,47,Married,Lead,8,Legal,Full-Time,3,3,...,7.9,Motorbike,16,8,22,4,Bachelor,False,54.0,4
1725,2796,Male,31,Married,Mid,5,IT,Part-Time,4,5,...,5.2,Bike,4,3,11,0,Bachelor,True,32.5,5
1379,580,Other,26,Single,Junior,4,Operations,Part-Time,3,5,...,7.4,Walk,1,1,10,0,High School,False,22.0,5
1023,2659,Female,48,Married,Mid,10,Operations,Full-Time,1,2,...,6.2,Public Transport,23,8,13,0,Bachelor,False,35.0,3
196,2,Female,32,Single,Senior,10,HR,Full-Time,5,5,...,6.7,Motorbike,13,3,16,5,Bachelor,False,45.0,4
2609,1187,Female,32,Single,Senior,8,Operations,Part-Time,2,5,...,6.5,Walk,1,3,19,5,Bachelor,False,44.0,2
2833,2120,Other,43,Single,Senior,4,IT,Full-Time,3,1,...,7.3,Motorbike,5,7,25,8,Bachelor,True,42.0,1
390,1487,Female,35,Married,Mid,13,IT,Full-Time,3,5,...,6.3,Car,25,4,13,0,Bachelor,True,36.5,4
2951,2598,Male,44,Married,Lead,22,Sales,Contract,2,5,...,6.5,Motorbike,14,7,22,2,PhD,False,61.0,4

In [47]:
sample_size[sample_size['Age'] < 25]

Empty DataFrame
Columns: [EmpID, Gender, Age, MaritalStatus, JobLevel, Experience, Dept, EmpType, WLB, WorkEnv, PhysicalActivityHours, Workload, Stress, SleepHours, CommuteMode, CommuteDistance, NumCompanies, TeamSize, NumReports, EduLevel, haveOT, TrainingHoursPerYear, JobSatisfaction]
Index: []

[0 rows x 23 columns]

In [48]:
sample_size.info

<bound method DataFrame.info of       EmpID  Gender  Age MaritalStatus JobLevel  Experience        Dept  \
831     631  Female   27        Single   Junior           5  Operations
2906   1539    Male   47       Married     Lead           8       Legal
1725   2796    Male   31       Married      Mid           5          IT
1379    580   Other   26        Single   Junior           4  Operations
1023   2659  Female   48       Married      Mid          10  Operations
196       2  Female   32        Single   Senior          10          HR
2609   1187  Female   32        Single   Senior           8  Operations
2833   2120   Other   43        Single   Senior           4          IT
390    1487  Female   35       Married      Mid          13          IT
2951   2598    Male   44       Married     Lead          22       Sales

        EmpType  WLB  WorkEnv  ...  SleepHours       CommuteMode  \
831   Part-Time    2        5  ...         6.8  Public Transport
2906  Full-Time    3        3  ...         7.9         Motorbike
1725  Part-Time    4        5  ...         5.2              Bike
1379  Part-Time    3        5  ...         7.4              Walk
1023  Full-Time    1        2  ...         6.2  Public Transport
196   Full-Time    5        5  ...         6.7         Motorbike
2609  Part-Time    2        5  ...         6.5              Walk
2833  Full-Time    3        1  ...         7.3         Motorbike
390   Full-Time    3        5  ...         6.3               Car
2951   Contract    2        5  ...         6.5         Motorbike

      CommuteDistance  NumCompanies TeamSize  NumReports     EduLevel  haveOT  \
831                25             1        9           0     Bachelor   False
2906               16             8       22           4     Bachelor   False
1725                4             3       11           0     Bachelor    True
1379                1             1       10           0  High School   False
1023               23             8       13           0     Bachelor   False
196                13             3       16           5     Bachelor   False
2609                1             3       19           5     Bachelor   False
2833                5             7       25           8     Bachelor    True
390                25             4       13           0     Bachelor    True
2951               14             7       22           2          PhD   False

      TrainingHoursPerYear JobSatisfaction
831                   22.5               3
2906                  54.0               4
1725                  32.5               5
1379                  22.0               5
1023                  35.0               3
196                   45.0               4
2609                  44.0               2
2833                  42.0               1
390                   36.5               4
2951                  61.0               4

[10 rows x 23 columns]>

In [49]:
d = {"b": 1, "a": 0, "c": 2}

pd.Series(d)

bet = {"shoe": 200, "book": 300, "snacks": 400, "rent": 500, "vacation": 600, "data_sub.": 1000}
#pd.Series(bet)
for key, value in bet.items():
    total = sum(bet.values())
    print(f"Total Sum = {total}")
    break
    if value <= 100:
         print(value)
    elif value > 500:
         print(value)
    elif value == max:
         print(value)

Total Sum = 3000

In [50]:
bet = {"shoe": 200, "book": 300, "snacks": 400, "rent": 500, "vacation": 600, "data_sub.": 1000}
pd.Series(bet)

shoe          200
book          300
snacks        400
rent          500
vacation      600
data_sub.    1000
dtype: int64

In [51]:
working_data = pd.read_csv("employee_survey.csv")
working_data.info()


for key, value in working_data.items():
    print(f"{key} is Key")
    print(f"{value} is Value")

    add = sum(value)
    print(add, "Total sum of sample")

    f = len(value)
    print(f, "Number of occurrences")

    mean = sum(value) / len(value)
    print(mean)
    #OR
    _x = add / f
    print(_x, "is our mean value")

    #big = max(value)
    #print(big, "is our max value")

    #small = min(value)
    #print(small, "is our min value")

    #R = big - small
    #print(R, "is our range value")

    std = value.std()
    print(std, "is our standard deviation value")
    break
working_data.describe()

<class 'pandas.DataFrame'>
RangeIndex: 3025 entries, 0 to 3024
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   EmpID                  3025 non-null   int64
 1   Gender                 3025 non-null   str
 2   Age                    3025 non-null   int64
 3   MaritalStatus          3025 non-null   str
 4   JobLevel               3025 non-null   str
 5   Experience             3025 non-null   int64
 6   Dept                   3025 non-null   str
 7   EmpType                3025 non-null   str
 8   WLB                    3025 non-null   int64
 9   WorkEnv                3025 non-null   int64
 10  PhysicalActivityHours  3025 non-null   float64
 11  Workload               3025 non-null   int64
 12  Stress                 3025 non-null   int64
 13  SleepHours             3025 non-null   float64
 14  CommuteMode            3025 non-null   str
 15  CommuteDistance        3025 non-null   int64
 16  NumCompanies           3025 non-null   int64
 17  TeamSize               3025 non-null   int64
 18  NumReports             3025 non-null   int64
 19  EduLevel               3025 non-null   str
 20  haveOT                 3025 non-null   bool
 21  TrainingHoursPerYear   3025 non-null   float64
 22  JobSatisfaction        3025 non-null   int64
dtypes: bool(1), float64(3), int64(12), str(7)
memory usage: 523.0 KB
EmpID is Key
0          6
1         11
2         33
3         20
4         28
        ...
3020    2070
3021    2072
3022    2145
3023    2168
3024    2183
Name: EmpID, Length: 3025, dtype: int64 is Value
4576825 Total sum of sample
3025 Number of occurrences
1513.0
1513.0 is our mean value
873.3866077898531 is our standard deviation value

,EmpID,Age,Experience,WLB,WorkEnv,PhysicalActivityHours,Workload,Stress,SleepHours,CommuteDistance,NumCompanies,TeamSize,NumReports,TrainingHoursPerYear,JobSatisfaction
count,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000
mean,1513.000000,35.741818,9.082645,3.061157,3.029091,2.029620,2.966612,1.736529,7.005983,13.473719,4.253554,16.516033,2.383140,37.301653,3.386777
std,873.386608,10.191833,7.073344,1.447001,1.415317,0.966014,1.401486,1.064242,1.002652,8.395249,3.382501,6.638419,3.058131,13.569772,1.260599
min,1.000000,22.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,4.000000,1.000000,0.000000,5.000000,0.000000,10.000000,1.000000
25%,757.000000,27.000000,3.000000,2.000000,2.000000,1.300000,2.000000,1.000000,6.300000,6.000000,1.000000,11.000000,0.000000,23.500000,3.000000
50%,1513.000000,34.000000,8.000000,3.000000,3.000000,2.000000,3.000000,1.000000,7.000000,13.000000,4.000000,16.000000,0.000000,40.000000,4.000000
75%,2269.000000,43.000000,14.000000,4.000000,4.000000,2.700000,4.000000,2.000000,7.700000,21.000000,7.000000,22.000000,5.000000,46.500000,4.000000
max,3025.000000,60.000000,29.000000,5.000000,5.000000,5.000000,5.000000,5.000000,10.000000,29.000000,12.000000,30.000000,9.000000,64.500000,5.000000

In [52]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Bennie", "Paul", "Peter", "John"],
    "Age": [23,33,54,19],
    "Sex": ["Female", "Male", "Male", "Male"],
})
df
df["Age"]

for value in df.Age:
    print(value)
    if value > 50:
        print(f"Worker should be considered to retire at {value}")
        break
df["Name"]
df
for name in df.Name:
    if "Paul" and "John" in name:
        print(f"{name} has no duplicate")
        break


df.describe()

23
33
54
Worker should be considered to retire at 54
John has no duplicate

             Age
count   4.000000
mean   32.250000
std    15.649814
min    19.000000
25%    22.000000
50%    28.000000
75%    38.250000
max    54.000000

In [55]:
employee = pd.read_csv("employee_survey.csv")
employee

,EmpID,Gender,Age,MaritalStatus,JobLevel,Experience,Dept,EmpType,WLB,WorkEnv,...,SleepHours,CommuteMode,CommuteDistance,NumCompanies,TeamSize,NumReports,EduLevel,haveOT,TrainingHoursPerYear,JobSatisfaction
0,6,Male,32,Married,Mid,7,IT,Full-Time,1,1,...,7.6,Car,20,3,12,0,Bachelor,True,33.5,5
1,11,Female,34,Married,Mid,12,Finance,Full-Time,1,1,...,7.9,Car,15,4,11,0,Bachelor,False,36.0,5
2,33,Female,23,Single,Intern/Fresher,1,Marketing,Full-Time,2,4,...,6.5,Motorbike,17,0,30,0,Bachelor,True,10.5,5
3,20,Female,29,Married,Junior,6,IT,Contract,2,2,...,7.5,Public Transport,13,2,9,0,Bachelor,True,23.0,5
4,28,Other,23,Single,Junior,1,Sales,Part-Time,3,1,...,4.9,Car,20,0,7,0,Bachelor,False,20.5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3020,2070,Male,47,Married,Lead,16,Marketing,Part-Time,1,3,...,6.8,Public Transport,15,8,28,8,Master,False,58.0,1
3021,2072,Female,47,Married,Lead,8,IT,Contract,3,1,...,6.9,Car,28,8,21,8,Master,True,54.0,1
3022,2145,Male,41,Married,Lead,17,IT,Full-Time,1,1,...,6.1,Public Transport,9,6,23,3,Master,True,58.5,1
3023,2168,Female,54,Married,Lead,16,IT,Full-Time,1,5,...,7.7,Public Transport,18,10,30,7,Master,True,58.0,1
3024,2183,Female,44,Married,Lead,22,Marketing,Full-Time,3,3,...,6.2,Car,10,7,29,4,PhD,False,61.0,1

In [57]:
employee.head(10)

,EmpID,Gender,Age,MaritalStatus,JobLevel,Experience,Dept,EmpType,WLB,WorkEnv,...,SleepHours,CommuteMode,CommuteDistance,NumCompanies,TeamSize,NumReports,EduLevel,haveOT,TrainingHoursPerYear,JobSatisfaction
0,6,Male,32,Married,Mid,7,IT,Full-Time,1,1,...,7.6,Car,20,3,12,0,Bachelor,True,33.5,5
1,11,Female,34,Married,Mid,12,Finance,Full-Time,1,1,...,7.9,Car,15,4,11,0,Bachelor,False,36.0,5
2,33,Female,23,Single,Intern/Fresher,1,Marketing,Full-Time,2,4,...,6.5,Motorbike,17,0,30,0,Bachelor,True,10.5,5
3,20,Female,29,Married,Junior,6,IT,Contract,2,2,...,7.5,Public Transport,13,2,9,0,Bachelor,True,23.0,5
4,28,Other,23,Single,Junior,1,Sales,Part-Time,3,1,...,4.9,Car,20,0,7,0,Bachelor,False,20.5,5
5,45,Female,33,Married,Mid,10,Operations,Part-Time,2,3,...,6.2,Car,8,3,13,0,Bachelor,False,35.0,5
6,21,Female,26,Single,Junior,4,Sales,Full-Time,2,2,...,5.8,Car,29,1,8,0,Bachelor,True,22.0,5
7,44,Male,24,Single,Junior,2,IT,Full-Time,1,3,...,5.7,Car,29,0,10,0,Bachelor,True,21.0,5
8,7,Female,29,Married,Junior,7,Marketing,Full-Time,4,3,...,8.2,Car,13,2,8,0,Bachelor,False,23.5,5
9,15,Female,24,Single,Mid,2,Marketing,Part-Time,5,5,...,8.5,Bike,9,0,10,0,Bachelor,False,31.0,5

In [59]:
employee["Gender"]

0         Male
1       Female
2       Female
3       Female
4        Other
         ...
3020      Male
3021    Female
3022      Male
3023    Female
3024    Female
Name: Gender, Length: 3025, dtype: str

In [61]:
employee["Age"]

0       32
1       34
2       23
3       29
4       23
        ..
3020    47
3021    47
3022    41
3023    54
3024    44
Name: Age, Length: 3025, dtype: int64

In [80]:
employee["Age"].max()
for value in employee.Age :
    print(value)
    if value >= 33:
        print(value)
        break

for num in employee.Experience:
    if num > 15:
        print(f"{num} is considered best job total working experience")

32
34
34
23 is considered best job total working experience
18 is considered best job total working experience
26 is considered best job total working experience
25 is considered best job total working experience
17 is considered best job total working experience
16 is considered best job total working experience
25 is considered best job total working experience
23 is considered best job total working experience
21 is considered best job total working experience
21 is considered best job total working experience
16 is considered best job total working experience
16 is considered best job total working experience
19 is considered best job total working experience
17 is considered best job total working experience
17 is considered best job total working experience
24 is considered best job total working experience
16 is considered best job total working experience
20 is considered best job total working experience
17 is considered best job total working experience
16 is considered best job total working experience
24 is considered best job total working experience
16 is considered best job total working experience
16 is considered best job total working experience
16 is considered best job total working experience
19 is considered best job total working experience
24 is considered best job total working experience
22 is considered best job total working experience
16 is considered best job total working experience
17 is considered best job total working experience
16 is considered best job total working experience
17 is considered best job total working experience
18 is considered best job total working experience
22 is considered best job total working experience
17 is considered best job total working experience
23 is considered best job total working experience
17 is considered best job total working experience
16 is considered best job total working experience
23 is considered best job total working experience
18 is considered best job total working experience
21 is considered best job total working experience
27 is considered best job total working experience
20 is considered best job total working experience
18 is considered best job total working experience
18 is considered best job total working experience
18 is considered best job total working experience
20 is considered best job total working experience
17 is considered best job total working experience
25 is considered best job total working experience
20 is considered best job total working experience
21 is considered best job total working experience
21 is considered best job total working experience
16 is considered best job total working experience
24 is considered best job total working experience
16 is considered best job total working experience
20 is considered best job total working experience
21 is considered best job total working experience
18 is considered best job total working experience
17 is considered best job total working experience
17 is considered best job total working experience
17 is considered best job total working experience
29 is considered best job total working experience
17 is considered best job total working experience
20 is considered best job total working experience
17 is considered best job total working experience
21 is considered best job total working experience
25 is considered best job total working experience
17 is considered best job total working experience
23 is considered best job total working experience
18 is considered best job total working experience
23 is considered best job total working experience
17 is considered best job total working experience
26 is considered best job total working experience
18 is considered best job total working experience
19 is considered best job total working experience
18 is considered best job total working experience
21 is considered best job total working experience
24 is considered best job total working experience
23 is considered best job total working experience
17 is considered best job total working experience
22 is considered best job total working experience
19 is considered best job total working experience
24 is considered best job total working experience
25 is considered best job total working experience
17 is considered best job total working experience
23 is considered best job total working experience
22 is considered best job total working experience
29 is considered best job total working experience
18 is considered best job total working experience
17 is considered best job total working experience
17 is considered best job total working experience
21 is considered best job total working experience
29 is considered best job total working experience
22 is considered best job total working experience
17 is considered best job total working experience
18 is considered best job total working experience
23 is considered best job total working experience
18 is considered best job total working experience
16 is considered best job total working experience
25 is considered best job total working experience
19 is considered best job total working experience
19 is considered best job total working experience
20 is considered best job total working experience
16 is considered best job total working experience
17 is considered best job total working experience
24 is considered best job total working experience
16 is considered best job total working experience
18 is considered best job total working experience
25 is considered best job total working experience
22 is considered best job total working experience
27 is considered best job total working experience
27 is considered best job total working experience
16 is considered best job total working experience
16 is considered best job total working experience
21 is considered best job total working experience
17 is considered best job total working experience
18 is considered best job total working experience
19 is considered best job total working experience
19 is considered best job total working experience
19 is considered best job total working experience
23 is considered best job total working experience
24 is considered best job total working experience
26 is considered best job total working experience
17 is considered best job total working experience
19 is considered best job total working experience
22 is considered best job total working experience
24 is considered best job total working experience
18 is considered best job total working experience
17 is considered best job total working experience
16 is considered best job total working experience
16 is considered best job total working experience
17 is considered best job total working experience
21 is considered best job total working experience
22 is considered best job total working experience
24 is considered best job total working experience
22 is considered best job total working experience
16 is considered best job total working experience
21 is considered best job total working experience
18 is considered best job total working experience
18 is considered best job total working experience
17 is considered best job total working experience
17 is considered best job total working experience
16 is considered best job total working experience
20 is considered best job total working experience
20 is considered best job total working experience
24 is considered best job total working experience
25 is considered best job total working experience
16 is considered best job total working experience
18 is considered best job total working experience
23 is considered best job total working experience
17 is considered best job total working experience
21 is considered best job total working experience
17 is considered best job total working experience
26 is considered best job total working experience
19 is considered best job total working experience
18 is considered best job total working experience
18 is considered best job total working experience
17 is considered best job total working experience
29 is considered best job total working experience
16 is considered best job total working experience
24 is considered best job total working experience
23 is considered best job total working experience
17 is considered best job total working experience
17 is considered best job total working experience
25 is considered best job total working experience
16 is considered best job total working experience
16 is considered best job total working experience
25 is considered best job total working experience
17 is considered best job total working experience
16 is considered best job total working experience
16 is considered best job total working experience
16 is considered best job total working experience
17 is considered best job total working experience
21 is considered best job total working experience
16 is considered best job total working experience
27 is considered best job total working experience
28 is considered best job total working experience
26 is considered best job total working experience
16 is considered best job total working experience
26 is considered best job total working experience
19 is considered best job total working experience
18 is considered best job total working experience
16 is considered best job total working experience
17 is considered best job total working experience
22 is considered best job total working experience
23 is considered best job total working experience
16 is considered best job total working experience
25 is considered best job total working experience
19 is considered best job total working experience
27 is considered best job total working experience
21 is considered best job total working experience
20 is considered best job total working experience
28 is considered best job total working experience
21 is considered best job total working experience
17 is considered best job total working experience
26 is considered best job total working experience
18 is considered best job total working experience
16 is considered best job total working experience
20 is considered best job total working experience
18 is considered best job total working experience
27 is considered best job total working experience
16 is considered best job total working experience
24 is considered best job total working experience
16 is considered best job total working experience
23 is considered best job total working experience
23 is considered best job total working experience
16 is considered best job total working experience
16 is considered best job total working experience
16 is considered best job total working experience
18 is considered best job total working experience
20 is considered best job total working experience
25 is considered best job total working experience
27 is considered best job total working experience
27 is considered best job total working experience
17 is considered best job total working experience
16 is considered best job total working experience
19 is considered best job total working experience
16 is considered best job total working experience
24 is considered best job total working experience
16 is considered best job total working experience
16 is considered best job total working experience
17 is considered best job total working experience
18 is considered best job total working experience
16 is considered best job total working experience
21 is considered best job total working experience
20 is considered best job total working experience
19 is considered best job total working experience
24 is considered best job total working experience
18 is considered best job total working experience
27 is considered best job total working experience
19 is considered best job total working experience
17 is considered best job total working experience
26 is considered best job total working experience
16 is considered best job total working experience
17 is considered best job total working experience
16 is considered best job total working experience
17 is considered best job total working experience
23 is considered best job total working experience
24 is considered best job total working experience
20 is considered best job total working experience
17 is considered best job total working experience
27 is considered best job total working experience
23 is considered best job total working experience
17 is considered best job total working experience
20 is considered best job total working experience
16 is considered best job total working experience
19 is considered best job total working experience
24 is considered best job total working experience
18 is considered best job total working experience
25 is considered best job total working experience
27 is considered best job total working experience
24 is considered best job total working experience
27 is considered best job total working experience
21 is considered best job total working experience
17 is considered best job total working experience
17 is considered best job total working experience
25 is considered best job total working experience
22 is considered best job total working experience
21 is considered best job total working experience
16 is considered best job total working experience
19 is considered best job total working experience
26 is considered best job total working experience
26 is considered best job total working experience
26 is considered best job total working experience
19 is considered best job total working experience
18 is considered best job total working experience
16 is considered best job total working experience
20 is considered best job total working experience
17 is considered best job total working experience
28 is considered best job total working experience
22 is considered best job total working experience
18 is considered best job total working experience
17 is considered best job total working experience
27 is considered best job total working experience
26 is considered best job total working experience
22 is considered best job total working experience
19 is considered best job total working experience
24 is considered best job total working experience
25 is considered best job total working experience
16 is considered best job total working experience
17 is considered best job total working experience
22 is considered best job total working experience
27 is considered best job total working experience
27 is considered best job total working experience
18 is considered best job total working experience
24 is considered best job total working experience
21 is considered best job total working experience
21 is considered best job total working experience
22 is considered best job total working experience
18 is considered best job total working experience
29 is considered best job total working experience
28 is considered best job total working experience
27 is considered best job total working experience
18 is considered best job total working experience
22 is considered best job total working experience
16 is considered best job total working experience
22 is considered best job total working experience
16 is considered best job total working experience
24 is considered best job total working experience
22 is considered best job total working experience
17 is considered best job total working experience
19 is considered best job total working experience
28 is considered best job total working experience
16 is considered best job total working experience
22 is considered best job total working experience
23 is considered best job total working experience
18 is considered best job total working experience
17 is considered best job total working experience
20 is considered best job total working experience
25 is considered best job total working experience
17 is considered best job total working experience
23 is considered best job total working experience
17 is considered best job total working experience
17 is considered best job total working experience
17 is considered best job total working experience
24 is considered best job total working experience
19 is considered best job total working experience
26 is considered best job total working experience
18 is considered best job total working experience
20 is considered best job total working experience
20 is considered best job total working experience
18 is considered best job total working experience
25 is considered best job total working experience
19 is considered best job total working experience
24 is considered best job total working experience
20 is considered best job total working experience
21 is considered best job total working experience
21 is considered best job total working experience
18 is considered best job total working experience
21 is considered best job total working experience
26 is considered best job total working experience
25 is considered best job total working experience
20 is considered best job total working experience
21 is considered best job total working experience
23 is considered best job total working experience
23 is considered best job total working experience
24 is considered best job total working experience
23 is considered best job total working experience
24 is considered best job total working experience
19 is considered best job total working experience
16 is considered best job total working experience
19 is considered best job total working experience
20 is considered best job total working experience
16 is considered best job total working experience
21 is considered best job total working experience
22 is considered best job total working experience
18 is considered best job total working experience
28 is considered best job total working experience
25 is considered best job total working experience
24 is considered best job total working experience
16 is considered best job total working experience
24 is considered best job total working experience
23 is considered best job total working experience
17 is considered best job total working experience
29 is considered best job total working experience
25 is considered best job total working experience
17 is considered best job total working experience
16 is considered best job total working experience
24 is considered best job total working experience
16 is considered best job total working experience
18 is considered best job total working experience
22 is considered best job total working experience
18 is considered best job total working experience
21 is considered best job total working experience
16 is considered best job total working experience
29 is considered best job total working experience
23 is considered best job total working experience
22 is considered best job total working experience
16 is considered best job total working experience
17 is considered best job total working experience
20 is considered best job total working experience
24 is considered best job total working experience
25 is considered best job total working experience
26 is considered best job total working experience
18 is considered best job total working experience
26 is considered best job total working experience
17 is considered best job total working experience
18 is considered best job total working experience
24 is considered best job total working experience
16 is considered best job total working experience
20 is considered best job total working experience
22 is considered best job total working experience
22 is considered best job total working experience
23 is considered best job total working experience
17 is considered best job total working experience
19 is considered best job total working experience
17 is considered best job total working experience
16 is considered best job total working experience
26 is considered best job total working experience
22 is considered best job total working experience
16 is considered best job total working experience
18 is considered best job total working experience